services:
  console: &console
    build:
      context: docker/
    environment:
      PLATFORMIO_CORE_DIR: /app/vendor
    volumes:
      - .:/app
      - /tmp:/tmp
      - ~/.bash_history:/root/.bash_history
    working_dir: /app
    command: /bin/bash
